pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Muaz-Ar/jenkins_demo'
            }
        }
        stage('Build') {
            steps {
                sh 'pip install -r projekt_docker/requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 projekt_docker/tests.py'
            }
        }
        stage('Run') {
            steps {
                sh 'python3 projekt_docker/main.py'
            }
        }
    }
}